FROM node:24-bookworm-slim@sha256:0e0ff40c39bc087845bfb27465a0df4ea419520094bc35842ff83dd8cbe6f9b6
ARG APP_DIR
WORKDIR /app
COPY ${APP_DIR}/package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund
COPY ${APP_DIR}/ ./
USER node
CMD ["node", "server.js"]
