FROM node:24-bookworm-slim@sha256:0e0ff40c39bc087845bfb27465a0df4ea419520094bc35842ff83dd8cbe6f9b6 AS build
ARG APP_DIR
WORKDIR /app
COPY ${APP_DIR}/package*.json ./
RUN npm ci --no-audit --no-fund
COPY ${APP_DIR}/ ./
ENV VITE_BACKEND_URL=/api
ENV VITE_API_URL=/api/admin
RUN npm run build
FROM nginx:stable-alpine@sha256:0985e772fb9f729e6fa0980da05fca5d9c468e870eed43071545afa9d2e27d94
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
